// <auto-generated />
namespace MvcTemplate.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BookAuthorsAndUserLibrary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookAuthorsAndUserLibrary));
        
        string IMigrationMetadata.Id
        {
            get { return "201910250906212_BookAuthorsAndUserLibrary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
